---
layout: post
title: try-finally보다는 try-with-resources를 사용하라
excerpt: try-with-resources 는 자바7부터 지원되었던 기능이지만, 제대로 활용해본적이 없다. 실제로 회사에서도 아직 try-finally 구문을 사용하고 있고 나 또한 전임자가 이렇게 했으니 그냥 따라하자는 식으로 많이 쓴것 같다. 향후에는 적극적으로 활용할 수 있도록 try-with-resources 문법에 대해서 잘 알아두도록 하자.
categories: [EffectiveJava]
tags: [try-with-resources, try-finally, AutoCloseable]
---

### try-finally

자바 라이브러리에는 close 메서드를 호출해 직접 닫아줘야 하는 자원이 많다.

자원 닫기는 클라이언트가 놓치기 쉬워서 예측할 수 없는 성능 문제로 이어지기도 한다.

~~~java
static String firstLineOfFile(String path) throws IOException {
    BufferedReader br = new BufferedReader(new FileReader(path));
    try {
        return br.readLine();
    } finally {
        br.close();  
    }
}
~~~


나쁘지 않지만, 자원을 하나 더 사용한다면 어떨까?

~~~java
static void copy(String src, String dst) throws IOException {
    InputStream in = new FileInputStream(src);
    try {
        OutputStream out = new FileOutputStream(dst);
        try {
            byte[] buf = new byte[BUFFER_SIZE];
            int n;
            while ((n = in.read(buf)) >= 0)
                out.write(buf, 0, n);
        } finally {
            out.close();
        }
    } finally {
        in.close();
    }
}
~~~


자원이 생기는 만큼 계속해서 finally 구문에서 close 를 명시해야한다.

또한 예외는 try 블록과 finally 블록 모두에서 발생할 수 있는데, 예컨데 기기에 물리적인 문제가 생긴다면 firstLineOfFile 메서드 안의 readLine 메서드가 예외를 던지고, 같은 이유로 close 메서드도 실패할 것이다.

이런 상황이라면 두번째 예외가 첫 번째 예외를 완전히 집어삼켜 버린다.

이러한 문제들은 자바7 이 투척한 try-with-resources 덕에 모두 해결되었다.

<hr>

### try-with-resources


이 구조를 사용하려면 **해당 자원이 AutoCloseable 인터페이스를 구현**해야 한다.

아래는 위의 코드를 try-with-resources 를 사용해 재작성한 예다.

~~~java
static void copy(String src, String dst) throws IOException {
    try (InputStream in = new FileInputStream(src);
         OutputStream out = new FileOutputStream(dst)) {
        byte[] buf = new byte[BUFFER_SIZE];
        int n;
        while ((n = in.read(buf)) >= 0)
            out.write(buf, 0, n);
    }
}
~~~


try-with-resources 버전이 짧고 읽기 수월할 뿐 아니라 문제를 진단하기도 훨씬 좋다.

보통의 try-finally 에서처럼 try-with-resources 에서도 catch 절을 쓸 수 있다. 

catch 절 덕분에 try 문을 더 중첩하지 않고도 다수의 예외를 처리할 수 있다.

~~~java
static String firstLineOfFile(String path, String defaultVal) {
    try (BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    } catch (IOException e) {
        return defaultVal;
    }
}
~~~

<hr>

### 핵심 정리


꼭 회수해야 하는 자원을 다룰 때는 try-finally 말고, try-with-resources 를 사용하자.

예외는 없다. 코드는 더 짧고 분명해지고, 만들어지는 예외 정보도 훨씬 유용하다. 

try-finally 로 작성하면 실용적이지 못할 만큼 코드가 지저분해지는 경우라도, try-with-resources로는 정확하고 쉽게 자원을 회수할 수 있다.


### 참고
* EFFECTIVE JAVA 3/E - 아이템9. try-finally보다는 try-with-resources를 사용하라.
